# Generated by Django 4.2.1 on 2023-05-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='transmision',
            field=models.CharField(choices=[('AT', 'Automatica'), ('MT', 'Mecanica')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
